name: Publish Release

on:
  push:
    tags:
      - '*'
    workflow_dispatch:
      inputs:
        git-ref:
          description: Git Ref (Optional)
          required: false

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/gradle-build-action@v2

      - name: Publish release
        run: ./gradlew publishAllPublicationsToMavenCentralRepository
        env:
            ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
            ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
            ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SECRET_KEYS }}
